package dto;

public enum Category {
    FANTASY,ADVENTURE,ROMANCE,CONTEMPORARY,DYSTOPIAN
    ,MYSTERY,HORROR,THRILLER,PARANORMAL,HISTORICAL,FICTION,SCIENCE
    ,MEMOIR,COOKING,ART ,PERSONAL,DEVELOPMENT,MOTIVATIONAL,HEALTH,HISTORY,TRAVEL
    ,GUIDE,FAMILIES,HUMOR, CHILDREN
}